name: Deploy to GitHub Packages

on:
  push:
    branches: [ "master" ]   # agar asosiy branch "main" bo'lsa, "main" deb yozing
permissions:
  contents: read
  packages: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java & inject Maven credentials
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          server-id: github                # pom.xml <id> bilan bir xil
          server-username: GITHUB_ACTOR    # GitHub Actions foydalanuvchisi
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Deploy
        run: mvn -B clean deploy
