name: Deploy to GitHub Packages

on:
  push:
    branches: [ "master" ]   # agar default branch "main" bo'lsa, "main" deb yozing

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21 + Maven server creds
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          server-id: github                 # pom.xml dagi <id> bilan aynan bir xil
          server-username: GITHUB_ACTOR     # literal ism YO'Q!
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Deploy (verbose)
        run: mvn -B -e -X clean deploy
